export enum MachineType {
  LATHETURNING = 'LATHETURNING',

  LATHEREVOLVING = 'LATHEREVOLVING',

  LATHECAROUSEL = 'LATHECAROUSEL',

  BORING = 'BORING',

  COORDINATEBORING = 'COORDINATEBORING',

  DRILLING = 'DRILLING',

  PLANINGMORTISING = 'PLANINGMORTISING',

  DRAWING = 'DRAWING',

  GRINDING = 'GRINDING',

  TOOTHCUTTING = 'TOOTHCUTTING',

  SPECIAL = 'SPECIAL',

  CUTOFF = 'CUTOFF',
}
